// <auto-generated />
#nullable restore
using mazharenko.AoCAgent.Generator;
using mazharenko.AoCAgent;
using mazharenko.AoCAgent.Base;

namespace aoc.Day24
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("mazharenko.AoCAgent.Generator", "4.2.0")]
	partial class Day24
	{
		private interface IPart1 : IPart
		{
			long Solve(global::impl.day24.Ray[] input);
			global::impl.day24.Ray[] Parse(string input);
		}

		abstract internal class Part1Base
		{
			public virtual string Format(long res) => res!.ToString()!;
		}

		partial class Part1 : Part1Base, IPart1
		{
			public Settings Settings { get; } = new Settings
			{
				BypassNoExamples = true,
				ManualInterpretation = false
			};

			public System.Collections.Generic.IEnumerable<NamedExample> GetExamples()
			{
				yield break;
			}

			public string SolveString(string input)
			{
				var parsedInput = Parse(input);
				return Format(Solve(parsedInput));
			}

			private record Example(string Input, long Expectation) : IExample<long>
			{
				private string expectationFormatted = null !;
				private static global::aoc.Day24.Day24.Part1 part = new aoc.Day24.Day24.Part1();
				public long Run()
				{
					var parsedInput = part.Parse(Input);
					return part.Solve(parsedInput);
				}

				public long RunFormat(out string formatted)
				{
					var res = Run();
					formatted = part.Format(res);
					return res;
				}

				public string ExpectationFormatted => expectationFormatted ??= part.Format(Expectation);
			}
		}

		private interface IPart2 : IPart
		{
			string Solve(string input);
			string Parse(string input);
		}

		abstract internal class Part2Base
		{
			public virtual string Format(string res) => res!.ToString()!;
			public virtual string Parse(string input) => input.Trim();
		}

		partial class Part2 : Part2Base, IPart2
		{
			public Settings Settings { get; } = new Settings
			{
				BypassNoExamples = true,
				ManualInterpretation = false
			};

			public override string Format(string res) => res;
			public System.Collections.Generic.IEnumerable<NamedExample> GetExamples()
			{
				yield break;
			}

			public string SolveString(string input)
			{
				var parsedInput = Parse(input);
				return Format(Solve(parsedInput));
			}

			private record Example(string Input, string Expectation) : IExample<string>
			{
				private string expectationFormatted = null !;
				private static global::aoc.Day24.Day24.Part2 part = new aoc.Day24.Day24.Part2();
				public string Run()
				{
					var parsedInput = part.Parse(Input);
					return part.Solve(parsedInput);
				}

				public string RunFormat(out string formatted)
				{
					var res = Run();
					formatted = part.Format(res);
					return res;
				}

				public string ExpectationFormatted => expectationFormatted ??= part.Format(Expectation);
			}
		}
	}
}