using mazharenko.AoCAgent.Generator;

namespace aoc.Day11;

internal partial class Day11
{
	internal partial class Part1
	{
		private readonly Example example = new(
			"""
			...#......
			.......#..
			#.........
			..........
			......#...
			.#........
			.........#
			..........
			.......#..
			#...#.....
			""", 374);

		public char[,] Parse(string input) => day11.parse(input);
		public long Solve(char[,] input) => day11.solve1(input);
	}

[BypassNoExamples]	
internal partial class Part2
	{
		private readonly Example example = new(
			"""
			...#......
			.......#..
			#.........
			..........
			......#...
			.#........
			.........#
			..........
			.......#..
			#...#.....
			""", 82000210);
		public char[,] Parse(string input) => day11.parse(input);
		public long Solve(char[,] input) => day11.solve2(input);
	}
}